CREATE TABLE CATEGORIES(
	CategoryId int identity(1,1) PRIMARY KEY,
	NAME NVARCHAR(30) NOT NULL
)

CREATE TABLE PRODUCTS(
	ProductId int identity(1,1) PRIMARY KEY,
	NAME NVARCHAR(30) NOT NULL,
	PRICE decimal(5,2)  NOT NULL,
	CategoryId int NOT NULL
)

ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CategoryId)
REFERENCES CATEGORIES(CategoryId)

CREATE INDEX IX_CATEGORY_ID ON PRODUCTS(CategoryId)